#!/bin/bash
#Author nachos
# script daemon

# chkconfig: 2345 80 20
# description: runs bash script file as a service

. /etc/rc.d/init.d/functions

exec="/usr/sbin/${myservice}"
prog="${myservice}"
pidfile="/var/run/${myservice}.pid"

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog... "
    daemon --pidfile $pidfile  $exec
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog... "
    killproc -p $pidfile
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $pidfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


if [ "$EUID" -ne 0 ]; then
    echo "Insufficient privileges"
    exit 1
fi

case "$1" in
    start)
        #Only if not running,  start
        rh_status_q && echo "Process already started" && exit 0
        $1
        ;;
    stop)
        # Only if service is running stopt
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;    
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
        ;;
esac

exit $?

